auth_enabled: false

server:
  http_listen_port: 3100
  http_listen_address: 0.0.0.0
  log_level: debug

ingester:
  lifecycler:
    address: 0.0.0.0
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  wal:
    dir: /tmp/wal

schema_config:
  configs:
    - from: 2020-05-15
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb:
    directory: /tmp/loki/index

  filesystem:
    directory: /tmp/loki/chunks

limits_config:
  ingestion_rate_mb: 100
  ingestion_burst_size_mb: 200
  max_query_length: 721h
  max_query_parallelism: 32
  max_streams_per_user: 10000
  max_global_streams_per_user: 5000
  allow_structured_metadata: false
  reject_old_samples: false
  reject_old_samples_max_age: 168h
  creation_grace_period: 1h 